version: "3.6"
services:
  dbcaiuser:
    command:
    - -dbc
    - ./dbc --id
    image: deepinthought/ai-user-linux:0.3.4.1
    volumes:
    - type: volume
      source: dbc-ai-user-volume
      target: /dbc-ai-user
volumes:
  dbc-ai-user-volume:
    name: dbc-ai-user-volume
